# Supabase Edge Function configuration

[functions]

  [functions.ticketmaster]
  verify_jwt = false

  [functions.spotify]
  verify_jwt = false

  [functions.sync-artist-songs]
  verify_jwt = false

  [functions.sync-popular-tours]
  verify_jwt = false

