// Auto-generated by Supabase CLI on 2025-08-10
// Do not edit manually. Run `mcp_supabase_generate_typescript_types` to regenerate.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]
