// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjnjlaatvbjglzvlbdre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqbmpsYWF0dmJqZ2x6dmxiZHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NzgyNzksImV4cCI6MjA1NDQ1NDI3OX0.VlfEVy6omBiPVzjI0fYoUGFGlBk6LlE1dNVKqSVSp1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);